= Theoretische Grundlagen von Dokumentation #linebreak() in agilen Projekten
== Grundlagen agiler Softwareentwicklung
Agile Softwareentwicklung bezeichnet einen iterativen und inkrementellen Ansatz, der kurze Entwicklungszyklen, frühes Feedback, enge Zusammenarbeit mit Stakeholdern und eine hohe Anpassungsfähigkeit gegenüber Veränderungen betont @articleAbrahamsson, @DYBA2008833. Anders als in stark planungsgetriebenen Modellen werden Anforderungen, Entwurf, Implementierung und Test nicht ausschließlich als nacheinander ablaufende Phasen verstanden. Stattdessen entstehen früh lauffähige Teilergebnisse, die regelmäßig überprüft und weiterentwickelt werden. Agile Methoden gelten daher als leichtgewichtige Vorgehensweisen für dynamische Projektumfelder, in denen Anforderungen zu Beginn nicht vollständig feststehen @articleAbrahamsson, @DYBA2008833.

Agilität bedeutet nicht lediglich Schnelligkeit, sondern vor allem den systematischen Umgang mit Unsicherheit. Fachliche Anforderungen, technische Bedingungen und organisatorische Prioritäten können sich während des Projektverlaufs verändern @articleConboy. Kurze Iterationen, Reviews, Retrospektiven und die kontinuierliche Abstimmung zwischen Entwicklung und Fachseite ermöglichen es, diese Veränderungen früh zu erkennen und in die weitere Planung einzubeziehen. Agile Entwicklung ist somit nicht mit ungeplantem Arbeiten gleichzusetzen, sondern verankert Anpassungsfähigkeit bewusst im Prozess @articleConboy.

Empirische Untersuchungen zeigen, dass Teamorientierung und ein funktionierender Informationsfluss wesentliche Voraussetzungen erfolgreicher agiler Projektarbeit sind @MOE2010480. Direkte Kommunikation reduziert zwar formale Übergaben, kann eine dauerhafte und strukturierte Sicherung wichtiger Informationen jedoch nicht vollständig ersetzen @MOE2010480.

Die Wirksamkeit agiler Methoden hängt zudem vom Projektkontext ab. Projektgröße, Kritikalität, Teamstruktur, Lebensdauer und organisatorisches Umfeld beeinflussen, wie stark Prozesse formalisiert und Wissen dokumentiert werden muss @Boehm1504661. Agile Vorgehensweisen geben daher keinen vollständigen Verzicht auf Dokumentation vor, sondern verlangen eine bewusste Abwägung zwischen Flexibilität und notwendiger Nachvollziehbarkeit @Boehm1504661.
== Merkmale guter Projektdokumentation
Ein zentrales Qualitätsmerkmal von Projektdokumentation ist die Zweckorientierung @Lethbridge1241364. Jedes Dokument sollte eine konkrete Zielgruppe und Aufgabe besitzen, beispielsweise die Erklärung einer Architekturentscheidung, die Beschreibung einer Schnittstelle, die Unterstützung des Betriebs oder die Einarbeitung neuer Mitarbeitender @Lethbridge1241364. Untersuchungen zur Nutzung von Softwaredokumentation zeigen, dass Inhalte langfristig vor allem dann nützlich bleiben, wenn sie relevant und mit vertretbarem Aufwand pflegbar sind @Lethbridge1241364. Eine umfangreiche Informationssammlung ohne klaren Verwendungszweck erzeugt dagegen Pflegeaufwand, ohne die Projektarbeit entsprechend zu unterstützen @Lethbridge1241364.

Ebenso wichtig ist Aktualität @articleForward. Veraltete Dokumentation kann falsche Annahmen erzeugen und dadurch Fehlentscheidungen begünstigen. Aktualität bedeutet jedoch nicht, dass jedes Detail jederzeit vollständig beschrieben sein muss @articleForward. Vorrangig aktuell zu halten sind Informationen, die für Entwicklung, Wartung, Betrieb oder wiederkehrende Entscheidungen benötigt werden @articleForward. Die praktische Nützlichkeit hängt sowohl von der Relevanz der Inhalte als auch von geeigneten Werkzeugen und Pflegeprozessen ab @articleForward.

Dokumentation muss außerdem verständlich und auffindbar sein @articleTreude. Inhalte sollten auch von Personen nachvollzogen werden können, die nicht an der ursprünglichen Entscheidung beteiligt waren. Klare Sprache, konsistente Benennungen, eine geeignete Granularität und eine übersichtliche Struktur sind dafür ebenso wichtig wie fachliche Korrektheit @articleTreude. Selbst inhaltlich vollständige Dokumentation verliert einen großen Teil ihres Nutzens, wenn relevante Informationen nur mit hohem Suchaufwand gefunden werden können @articleTreude.

Ein weiteres Merkmal ist Nachvollziehbarkeit @Paetsch1231428, @Heikkilä7302452. Gute Dokumentation hält nicht nur fest, was umgesetzt wurde, sondern erläutert bei wesentlichen Entscheidungen auch die Gründe, Ausgangsbedingungen und gegebenenfalls verworfenen Alternativen. Bei Anforderungen ist zudem eine Verbindung zwischen fachlichem Bedarf, Umsetzung und Test sinnvoll @Paetsch1231428, @Heikkilä7302452. Agile Anforderungsarbeit kann diese Informationen leichtgewichtig durch User Stories, Backlogs, Akzeptanzkriterien und Testfälle sichern @Paetsch1231428, @Heikkilä7302452.

Schließlich muss Dokumentation wartbar sein @articleSouza. Inhalte, die nur mit hohem Aufwand aktualisiert werden können oder dieselben Informationen mehrfach enthalten, werden im Projektalltag schnell vernachlässigt @articleSouza. Dokumentation sollte deshalb möglichst nah am Arbeitsprozess entstehen, klar verantwortet und auf notwendige Ergänzungen zu Code, Tests und Tickets beschränkt werden @articleSouza. Für die spätere Wartung sind insbesondere Informationen zu Systemverhalten, Struktur und Änderungsfolgen relevant @articleSouza. 

Gute Projektdokumentation ist somit zweckmäßig, aktuell, verständlich, auffindbar, nachvollziehbar und mit angemessenem Aufwand pflegbar.
== Vorteile guter Projektdokumentation
Ein wesentlicher Vorteil guter Dokumentation liegt im Wissenstransfer @articleStettina. Softwareentwicklung ist wissensintensiv, wobei zentrale Informationen häufig in fachlichen Abwägungen, technischen Entscheidungen und dem Erfahrungswissen einzelner Personen liegen @articleStettina. Bleibt dieses Wissen ausschließlich implizit, entstehen Risiken bei Krankheit, Rollenwechsel, Fluktuation oder wachsender Teamgröße. Auch in agilen Teams bleibt Dokumentation deshalb notwendig, um Wissen dauerhaft verfügbar zu machen und Informationsverluste zu begrenzen @articleStettina.

Dokumentation unterstützt außerdem die Wartung und Weiterentwicklung langlebiger Systeme @Lethbridge1241364, @articleSouza. Änderungen werden häufig von Personen durchgeführt, die nicht an der ursprünglichen Implementierung beteiligt waren. Für sie sind Übersichten zu Architektur, Systemverhalten, Abhängigkeiten und Änderungsfolgen besonders relevant @articleSouza. Aufgabenbezogene Dokumentation erleichtert die Orientierung und verringert den Aufwand, Zusammenhänge ausschließlich aus dem Quellcode rekonstruieren zu müssen @Lethbridge1241364.

Gute Dokumentation verbessert die Kommunikation zwischen Rollen und Stakeholdern @Bjarnason6051639. Direkte Gespräche ermöglichen schnelle Abstimmung, sichern deren Ergebnisse jedoch nicht dauerhaft @Bjarnason6051639. Werden fachliche Annahmen, Entscheidungen oder technische Einschränkungen nicht festgehalten, können sie später unterschiedlich interpretiert werden. Kommunikationslücken können insbesondere in größeren Projekten zu Qualitätsproblemen, verfehlten Erwartungen und zusätzlichem Aufwand führen @Bjarnason6051639. Dokumentation schafft hier ein gemeinsames Referenzsystem @Bjarnason6051639.

Auch die Qualitätssicherung profitiert von dokumentierten Anforderungen, Akzeptanzkriterien, Testfällen und bekannten Einschränkungen @articleRamesh, @INAYAT2015915. Informelle Kommunikation bietet Flexibilität, kann jedoch zu unklaren oder widersprüchlichen Anforderungen führen @articleRamesh. Leichtgewichtige und laufend priorisierte Anforderungsartefakte verbinden Nachvollziehbarkeit mit der notwendigen Veränderbarkeit @INAYAT2015915.

Mit zunehmender Projektgröße und Lebensdauer steigt schließlich die organisatorische Bedeutung von Dokumentation @KASAULI2021110851. Wissen muss über Team- und Rollengrenzen hinweg verfügbar bleiben, besonders bei regulatorischen, betrieblichen oder vertraglichen Anforderungen @KASAULI2021110851. Untersuchungen zur großskaligen agilen Entwicklung zeigen, dass die Koordination von Anforderungen und Wissen in größeren Organisationen eine besondere Herausforderung darstellt @KASAULI2021110851. Dokumentation reduziert dabei die Abhängigkeit von informellen Kommunikationswegen und einzelnen Personen @KASAULI2021110851.
== Die Rolle von Dokumentationsaufwand in agilen Projekten
Empirische Untersuchungen zeigen, dass interne Dokumentation in agilen Teams gleichzeitig als notwendig und als häufig vernachlässigt wahrgenommen wird @articleStettina. In kleinen, stabilen Teams kann direkte Kommunikation einen Teil der formalen Dokumentation ersetzen @articleStettina. Mit wachsender Systemkomplexität, längerer Laufzeit, personellen Veränderungen und steigender Anzahl beteiligter Personen nimmt der Bedarf an dauerhaft verfügbarem Wissen jedoch zu @articleStettina. Der angemessene Aufwand muss deshalb kontextabhängig bestimmt werden @articleStettina.

Agile Dokumentation ist nicht mit möglichst wenig Dokumentation gleichzusetzen. Entscheidend ist der Nutzen der einzelnen Artefakte @Islam10197828. Die Literatur zeigt, dass in der Praxis unterschiedliche Auffassungen darüber bestehen, welche Inhalte in agilen Projekten festgehalten werden sollten @Islam10197828. Dokumentation muss daher bewusst gestaltet und in den Entwicklungsprozess integriert werden, statt lediglich nebenbei oder erst nach Abschluss einer Aufgabe zu entstehen @Islam10197828.

Wichtige Einflussfaktoren sind Teamgröße und Fluktuation, fachliche und technische Komplexität, Kritikalität, externe Schnittstellen, regulatorische Anforderungen und die erwartete Lebensdauer des Systems @Boehm1504661. In kleinen Projekten mit stabiler Teamzusammensetzung kann ein geringer formaler Umfang genügen @Boehm1504661. Bei großen, langlebigen oder kritischen Systemen ist eine stärkere Dokumentation erforderlich, weil Wissen über längere Zeit und für mehr Beteiligte verfügbar bleiben muss @Boehm1504661. Zu viel Formalisierung kann die Anpassungsfähigkeit einschränken, während zu wenig Struktur Risiken für Qualität, Koordination und Wartbarkeit erzeugt @Boehm1504661.

Dokumentation sollte deshalb inkrementell und arbeitsnah entstehen. Geeignet sind unter anderem User Stories, Akzeptanzkriterien, kurze Architekturentscheidungen, Schnittstellenbeschreibungen, Testdokumentation, Betriebsanleitungen und Onboarding-Hinweise @Heikkilä7302452, @INAYAT2015915. Diese Artefakte müssen nicht umfangreich sein, sollten aber Informationen sichern, die ohne Dokumentation nur schwer rekonstruierbar wären @Heikkilä7302452, @INAYAT2015915. Leichtgewichtige und iterativ gepflegte Artefakte können Flexibilität und Nachvollziehbarkeit miteinander verbinden @Heikkilä7302452, @INAYAT2015915.

Zusammenfassend ist der Aufwand damit als Investition in die zukünftige Entwicklungsfähigkeit zu betrachten. Kurzfristig kann weniger Dokumentation Zeit sparen. Langfristig können jedoch längere Einarbeitung, wiederholte Rückfragen, Fehlinterpretationen, technische Schulden und erschwerte Wartung höhere Kosten verursachen. Sinnvolle agile Dokumentation vermeidet deshalb unnötige oder redundante Inhalte, hält aber das für Verständnis, Weiterentwicklung und Betrieb wesentliche Wissen fest.