= Theoretische Grundlagen von Dokumentation #linebreak() in agilen Projekten
== Grundlagen agiler Softwareentwicklung
Agile Softwareentwicklung bezeichnet einen Ansatz der Softwareentwicklung, der auf kurze Entwicklungszyklen, frühes Feedback, enge Zusammenarbeit mit Stakeholdern und eine hohe Anpassungsfähigkeit gegenüber veränderten Anforderungen ausgerichtet ist. Im Gegensatz zu stark planungsgetriebenen Vorgehensmodellen wird der Entwicklungsprozess nicht primär als linearer Ablauf verstanden, bei dem Anforderungen, Entwurf, Implementierung und Test strikt nacheinander erfolgen. Vielmehr werden Softwareprodukte iterativ und inkrementell entwickelt, sodass lauffähige Teilergebnisse früh entstehen und regelmäßig überprüft werden können. Wissenschaftliche Übersichtsarbeiten beschreiben agile Methoden als leichtgewichtige Vorgehensweisen, die insbesondere auf dynamische Projektumfelder reagieren sollen, in denen Anforderungen nicht vollständig zu Beginn feststehen @articleAbrahamsson, @DYBA2008833.

Ein zentrales Merkmal agiler Entwicklung ist der Umgang mit Unsicherheit. Softwareprojekte sind häufig dadurch gekennzeichnet, dass fachliche Anforderungen, technische Rahmenbedingungen und organisatorische Prioritäten während des Projektverlaufs verändert werden. Agilität bedeutet daher nicht nur Schnelligkeit, sondern vor allem die Fähigkeit, Veränderungen wahrzunehmen, angemessen darauf zu reagieren und daraus Nutzen für das Projekt zu erzeugen @articleConboy. Agile Entwicklung ist somit nicht mit ungeplantem oder undiszipliniertem Arbeiten gleichzusetzen. Stattdessen wird Veränderbarkeit systematisch in den Entwicklungsprozess eingebaut, beispielsweise durch kurze Iterationen, regelmäßige Reviews, Retrospektiven und eine enge Abstimmung zwischen Entwicklungsteam und Fachseite.

Agile Projekte beruhen außerdem stark auf Kommunikation und Zusammenarbeit. Da Entscheidungen häufig dezentral im Team getroffen werden, gewinnen gemeinsame Zielbilder, geteiltes Fachwissen und ein funktionierender Informationsfluss eine hohe Bedeutung. Empirische Untersuchungen zu agilen Teams zeigen, dass Teamorientierung, Koordination und ein gemeinsames Verständnis wesentliche Faktoren für die Wirksamkeit agiler Projektarbeit sind @MOE2010480. Gleichzeitig können Spezialisierung, unklare Zuständigkeiten und fehlende Abstimmung die Teamleistung beeinträchtigen. Daraus ergibt sich, dass agile Softwareentwicklung zwar weniger formale Übergaben als klassische Vorgehensmodelle vorsieht, aber keineswegs ohne strukturierte Informationsweitergabe auskommt.

Die Vorteile agiler Vorgehensweisen liegen insbesondere in der frühen Lieferung nutzbarer Software, der stärkeren Einbindung von Kunden und Anwendern sowie der Möglichkeit, Anforderungen während des Projektverlaufs zu präzisieren. Studien zeigen einen positiven Zusammenhang zwischen agilen Methoden und Projekterfolg, weisen jedoch zugleich darauf hin, dass dieser Erfolg von der konkreten Umsetzung und vom Projektkontext abhängt @MOE2010480. Agile Methoden sind damit kein Selbstzweck, sondern müssen an Rahmenbedingungen wie Projektgröße, Kritikalität, Teamstruktur und organisatorisches Umfeld angepasst werden @Boehm1504661.
== Merkmale guter Projektdokumentation
Projektdokumentation umfasst alle schriftlichen, grafischen oder digitalen Artefakte, die Informationen über Anforderungen, Architektur, fachliche Entscheidungen, Schnittstellen, Code, Tests, Betrieb oder organisatorische Abläufe festhalten. In Softwareprojekten dient Dokumentation nicht nur der Ablage von Informationen, sondern vor allem der Kommunikation zwischen verschiedenen Beteiligten. Dazu gehören Entwicklerinnen und Entwickler, Product Owner, Fachabteilungen, Tester, Betriebsteams, neue Teammitglieder sowie externe Stakeholder. Gute Dokumentation ist daher nicht allein daran zu messen, ob sie umfangreich ist, sondern ob sie für ihre Zielgruppe verständlich, auffindbar, aktuell und handlungsrelevant ist.

Ein wesentliches Qualitätsmerkmal guter Dokumentation ist Zweckorientierung. Dokumentation sollte einen klaren Nutzen erfüllen, beispielsweise die Erklärung einer Architekturentscheidung, die Beschreibung einer Schnittstelle, die Nachvollziehbarkeit einer fachlichen Anforderung oder die Unterstützung bei der Einarbeitung. Empirische Untersuchungen zur Nutzung von Softwaredokumentation zeigen, dass Dokumentation in der Praxis häufig nicht konsequent aktualisiert wird und deshalb nur dann langfristig nützlich bleibt, wenn sie einfach, relevant und mit vertretbarem Aufwand pflegbar ist @Lethbridge1241364. Dokumentation sollte daher nicht möglichst vollständig im Sinne einer maximalen Informationssammlung sein, sondern so gestaltet werden, dass sie von den Beteiligten tatsächlich genutzt und fortgeschrieben wird.

Ein zweites Merkmal ist Aktualität. Veraltete Dokumentation kann in Softwareprojekten problematisch sein, weil sie falsche Annahmen erzeugt und dadurch Fehlentscheidungen begünstigt. Allerdings bedeutet Aktualität nicht, dass jedes Detail jederzeit vollständig dokumentiert sein muss. Vielmehr sollte vor allem jene Dokumentation aktuell gehalten werden, die für Entwicklung, Betrieb, Wartung oder Entscheidungen relevant ist. Die Nützlichkeit von Dokumentation hängt stark davon ab, ob die enthaltenen Informationen für die jeweilige Aufgabe relevant sind und ob geeignete Werkzeuge zur Erstellung und Pflege eingesetzt werden @articleForward.

Ein drittes Qualitätsmerkmal ist Verständlichkeit. Dokumentation muss so formuliert sein, dass sie auch von Personen verstanden werden kann, die nicht an der ursprünglichen Entscheidung oder Implementierung beteiligt waren. Dies betrifft insbesondere neue Teammitglieder, Wartungsentwickler oder Personen aus angrenzenden Rollen. Verständlichkeit hängt dabei von klarer Sprache, konsistenter Struktur, geeigneter Granularität und nachvollziehbaren Beispielen ab. Qualitätsmodelle für Softwaredokumentation betonen deshalb neben fachlicher Korrektheit auch Struktur, Lesbarkeit und Nutzbarkeit der Dokumentation @articleTreude.

Ein weiteres Merkmal ist Nachvollziehbarkeit. In Softwareprojekten müssen Entscheidungen häufig später rekonstruiert werden können, etwa wenn technische Schulden bewertet, Fehler analysiert oder Architekturänderungen geplant werden. Gute Dokumentation hält daher nicht nur fest, was entschieden wurde, sondern auch, warum eine Entscheidung getroffen wurde. Besonders bei fachlichen Anforderungen ist zudem die Verbindung zwischen Anforderung, Umsetzung und Test wichtig. Forschung zu agilem Requirements Engineering zeigt, dass agile Entwicklung und systematische Anforderungsarbeit nicht zwangsläufig im Widerspruch stehen. Anforderungen können in agilen Projekten beispielsweise durch User Stories, Backlogs, Akzeptanzkriterien und Testfälle leichtgewichtig dokumentiert werden @Paetsch1231428, @Heikkilä7302452.

Gute Projektdokumentation ist zuletzt grundsätzlich wartbar. Eine Dokumentation, die nur mit hohem Aufwand gepflegt werden kann, wird in agilen Projekten schnell vernachlässigt, weil Entwicklungszeit knapp ist und der Fokus auf lauffähiger Software liegt. Wartbarkeit bedeutet deshalb, dass Dokumentation möglichst nah an den Arbeitsprozessen entsteht, klar verantwortet wird und nicht unnötig redundant ist. Studien zur Nutzung und Relevanz von Softwaredokumentation zeigen, dass Dokumentation vor allem dann hilfreich ist, wenn sie aufgabenbezogen, aktuell und mit angemessenem Aufwand pflegbar bleibt @Lethbridge1241364, @articleForward. Zudem ist insbesondere für die spätere Wartung entscheidend, dass Dokumentation Systemverhalten, Struktur und Änderungsfolgen verständlich unterstützt @articleSouza. Wo Informationen bereits im Code, in Tests, im Backlog oder in automatisierten Systemen vorhanden sind, sollte Dokumentation diese Informationen daher nicht unreflektiert duplizieren, sondern ergänzen, einordnen und erklären. Gute Dokumentation ist somit zweckmäßig, aktuell, verständlich, nachvollziehbar und mit angemessenem Aufwand pflegbar.
== Vorteile guter Projektdokumentation
Gute Projektdokumentation erfüllt in Softwareprojekten mehrere Funktionen und hat mehrere Vorteile.

Ein zentraler Vorteil guter Projektdokumentation liegt im Wissenstransfer innerhalb des Teams. Softwareentwicklung ist wissensintensive Arbeit, bei der viele relevante Informationen nicht nur im Code, sondern auch in fachlichen Entscheidungen, technischen Abwägungen und implizitem Erfahrungswissen enthalten sind. Wenn dieses Wissen ausschließlich in den Köpfen einzelner Personen vorhanden ist, entstehen Risiken bei Krankheit, Rollenwechsel, Fluktuation oder wachsender Teamgröße. Empirische Untersuchungen zeigen, dass Dokumentation in agilen Teams trotz direkter Kommunikation notwendig bleibt, um internes Wissen verfügbar zu halten und Informationsverluste zu vermeiden @articleStettina. Dokumentation reduziert diese Abhängigkeit, indem zentrale Informationen dauerhaft festgehalten und für spätere Entwicklungs-, Wartungs- und Einarbeitungssituationen nutzbar bleiben @Lethbridge1241364.

Ein weiterer Vorteil besteht in der Unterstützung von Wartung und Weiterentwicklung bestehender Software. Gerade langlebige Softwaresysteme werden häufig von Personen bearbeitet und gewartet, die nicht an der ursprünglichen Entwicklung beteiligt waren. Untersuchungen zur Softwarewartung zeigen, dass bestimmte Dokumentationsartefakte besonders relevant sind, um Systemverhalten, Struktur und Änderungsfolgen zu verstehen @articleSouza. Auch Studien zur praktischen Nutzung von Dokumentation zeigen, dass Softwareentwickelnde Dokumentation in unterschiedlichen Arbeitssituationen verwenden, etwa zur Orientierung, Analyse und Veränderung bestehender Systeme @Lethbridge1241364.

Darüber hinaus verbessert Dokumentation die Kommunikation zwischen Rollen und Stakeholdern. In agilen Projekten wird zwar häufig direkte Kommunikation bevorzugt, jedoch kann diese nicht alle Informationsbedarfe dauerhaft abdecken. Entscheidungen aus Meetings, fachliche Annahmen oder technische Einschränkungen können verloren gehen, wenn sie nicht festgehalten werden. Fallstudien zu großskaliger Softwareentwicklung zeigen, dass Kommunikationslücken zu Qualitätsproblemen, verfehlten Kundenerwartungen und unnötigem Aufwand führen können @Bjarnason6051639. Dokumentation kann solche Lücken verringern, indem sie ein gemeinsames Referenzsystem schafft und zentrale Informationen für spätere Projektphasen verfügbar hält.

Gute Dokumentation unterstützt außerdem die Qualitätssicherung. Anforderungen, Akzeptanzkriterien, Testfälle und bekannte Einschränkungen schaffen eine Grundlage dafür, ob eine Umsetzung fachlich korrekt ist. Forschung zu agilem Requirements Engineering zeigt, dass informelle Kommunikation zwar Flexibilität ermöglicht, aber auch Risiken erzeugen kann, wenn Anforderungen unklar oder nur mündlich weitergegeben werden @articleRamesh. Systematische Literaturübersichten zeigen außerdem, dass agile Requirements-Engineering-Praktiken häufig auf kontinuierliche Priorisierung, enge Stakeholder-Kommunikation und leichtgewichtige Anforderungsartefakte setzen @INAYAT2015915. Dokumentation unterstützt diese Praktiken, wenn sie Anforderungen nicht unnötig verfestigt, sondern verständlich und überprüfbar macht.

Schließlich erhöht Dokumentation die organisatorische Nachvollziehbarkeit. Dies betrifft vor allem Projekte, die über längere Zeiträume laufen, mehrere Teams einbinden oder regulatorischen und betrieblichen Anforderungen unterliegen. Empirische Untersuchungen zu großskaliger agiler Systementwicklung zeigen, dass der Umgang mit Anforderungen und zugehörigem Wissen in größeren Organisationen eine besondere Herausforderung darstellt @KASAULI2021110851. Je stärker ein Projekt wächst, desto weniger reicht rein informelle Kommunikation aus. Dokumentation wird dann zu einem Mittel, um Wissen über Teamgrenzen hinweg verfügbar zu machen und Abstimmungsprobleme zu reduzieren.
== Die Rolle von Dokumentationsaufwand in agilen Projekten
Der Dokumentationsaufwand nimmt in agilen Projekten eine ambivalente Rolle ein. Einerseits wird Dokumentation benötigt, um Wissen zu sichern, Anforderungen nachvollziehbar zu machen und langfristige Wartbarkeit zu ermöglichen. Andererseits verursacht jede Dokumentationsaktivität Aufwand, der nicht unmittelbar in neue Funktionalität fließt. Agile Projekte stehen daher vor der Aufgabe, ein angemessenes Verhältnis zwischen Dokumentation und Entwicklungsfortschritt zu finden. Dabei geht es nicht um die Frage, ob dokumentiert werden soll, sondern welche Informationen in welcher Tiefe, zu welchem Zeitpunkt und für welche Zielgruppe dokumentiert werden müssen.

Empirische Untersuchungen zu interner Dokumentation in agilen Teams zeigen, dass Dokumentation in agilen Projekten zugleich als notwendig und häufig vernachlässigt wahrgenommen wird @articleStettina. Die stärkere Betonung direkter Kommunikation führt in der Praxis häufig dazu, dass Dokumentation reduziert wird. Dies kann in kleinen, stabilen und eng zusammenarbeitenden Teams zunächst funktionieren. Mit wachsender Systemkomplexität, längeren Projektlaufzeiten oder personellen Veränderungen steigt jedoch der Bedarf an dokumentiertem Wissen. Dokumentationsaufwand muss daher kontextabhängig bewertet werden.

Ein häufiger Fehler besteht darin, agile Dokumentation mit möglichst wenig Dokumentation gleichzusetzen. Die wissenschaftliche Literatur legt jedoch nahe, dass nicht die Menge, sondern der Nutzen der Dokumentation entscheidend ist. Systematische Literaturübersichten zu Dokumentationspraktiken in agiler Softwareentwicklung zeigen, dass in der Praxis unterschiedliche Auffassungen darüber bestehen, was in agilen Projekten dokumentiert werden sollte @Islam10197828. Daraus folgt, dass Dokumentation in agilen Projekten bewusst gestaltet werden muss und nicht lediglich nebenbei entstehen kann.

Der sinnvolle Dokumentationsaufwand hängt von mehreren Einflussfaktoren ab. Dazu gehören die Größe des Teams, die Fluktuation, die fachliche und technische Komplexität des Systems, die Kritikalität der Software, die Anzahl externer Schnittstellen, regulatorische Anforderungen und die erwartete Lebensdauer des Produkts. In kleinen Projekten mit stabiler Teamzusammensetzung kann ein geringerer formaler Dokumentationsumfang ausreichend sein. In größeren oder langfristig betriebenen Systemen ist dagegen eine stärkere Dokumentation notwendig, weil mehr Personen auf dieselben Informationen zugreifen müssen und Entscheidungen über längere Zeit nachvollziehbar bleiben sollen. Zu viel Formalisierung kann die Anpassungsfähigkeit reduzieren, während zu wenig Struktur Risiken für Qualität, Koordination und Wartbarkeit erzeugt @Boehm1504661.

Dokumentation sollte in agilen Projekten möglichst inkrementell und arbeitsnah entstehen. Das bedeutet, dass Dokumentation nicht erst am Ende eines Projekts nachträglich erstellt wird, sondern parallel zur Entwicklung gepflegt wird. Besonders geeignet sind leichtgewichtige Artefakte wie User Stories, Akzeptanzkriterien, Architekturentscheidungen, Schnittstellenbeschreibungen, Testdokumentation, Betriebsanleitungen und kurze Onboarding-Hinweise. Diese Artefakte müssen nicht zwangsläufig umfangreich sein, sollten aber zentrale Informationen enthalten, die ohne Dokumentation schwer rekonstruierbar wären. Forschung zu agilem Requirements Engineering zeigt, dass leichtgewichtige und iterativ gepflegte Artefakte dazu beitragen können, Dokumentation und Flexibilität miteinander zu verbinden @Heikkilä7302452, @INAYAT2015915.

Der Dokumentationsaufwand ist daher nicht isoliert zu betrachten, sondern als Investition in zukünftige Entwicklungsfähigkeit. Kurzfristig kann eine Reduzierung von Dokumentation Entwicklungszeit sparen. Langfristig kann fehlende Dokumentation jedoch zu höheren Kosten führen, etwa durch längere Einarbeitungszeiten, wiederholte Rückfragen, Fehlinterpretationen, technische Schulden oder erschwerte Wartung. Gute agile Dokumentation versucht, diese beiden Perspektiven auszubalancieren. Sie vermeidet unnötige Dokumente, hält aber diejenigen Informationen fest, die für Verständnis, Weiterentwicklung und Betrieb wesentlich sind.