= Bestimmung eines sinnvollen #linebreak() Dokumentationsumfangs
== Bewertungskriterien eines sinnvollen Umfangs
Aus den theoretischen Grundlagen lassen sich fünf Kriterien zur Bewertung des Dokumentationsumfangs ableiten.

Das erste Kriterium ist die Zweckmäßigkeit. Jedes Artefakt sollte einen konkreten Nutzen für Einarbeitung, Wartung, Fehleranalyse, Entscheidungsnachverfolgung oder Betrieb erfüllen. Dokumente ohne klare Zielgruppe oder Verwendung erzeugen zusätzlichen Pflegeaufwand und sollten reduziert, zusammengeführt oder archiviert werden.

Das zweite Kriterium ist die Relevanz der Inhalte. Vorrangig zu dokumentieren sind Informationen, die für das Systemverständnis notwendig und nicht ohne Weiteres aus Code, Tests oder Tickets erkennbar sind. Dazu gehören insbesondere fachliche Besonderheiten, zentrale Architekturentscheidungen, externe Schnittstellen, Betriebsabläufe sowie Abhängigkeiten zu anderen Systemen. Allgemein erkennbare oder automatisch erzeugbare Informationen müssen dagegen nicht mehrfach beschrieben werden.

Das dritte Kriterium ist die Aktualisierbarkeit. Der Umfang ist nur dann angemessen, wenn das Team die Inhalte im Projektalltag zuverlässig pflegen kann. Eine kleinere, aber aktuelle Dokumentationsbasis ist wertvoller als eine umfangreiche Sammlung veralteter Informationen. Häufig veränderliche Angaben sollten deshalb automatisiert erzeugt, zentral konfiguriert oder durch stabile Verweise ersetzt werden.

Das vierte Kriterium umfasst Auffindbarkeit und Verständlichkeit. Dokumentation erfüllt ihren Zweck nur, wenn relevante Inhalte schnell gefunden und von der jeweiligen Zielgruppe verstanden werden können. Einheitliche Benennungen, eine zentrale Navigation, klare Strukturen und eine passende Sprache sind daher wesentliche Bestandteile eines sinnvollen Umfangs. Verteilte Dubletten erhöhen dagegen sowohl Such- als auch Pflegeaufwand.

Das fünfte Kriterium ist der Projektkontext. Der erforderliche Umfang steigt mit Komplexität, Kritikalität, Lebensdauer, Teamgröße, regulatorischen Anforderungen und der Bedeutung externer Schnittstellen. Eine Dokumentation ist somit sinnvoll umfangreich, wenn sie die für Entwicklung, Wartung und Betrieb wesentlichen Informationen zuverlässig bereitstellt, ohne den agilen Prozess durch unnötige oder schwer pflegbare Inhalte zu belasten.
=== Zeitlicher und organisatorischer Umgang mit Dokumentation
Dokumentation sollte parallel zur Entwicklung entstehen und bei relevanten Änderungen unmittelbar angepasst werden @Heikkilä7302452, @INAYAT2015915. Leichtgewichtige, iterativ gepflegte Artefakte sichern notwendige Informationen, ohne die Anpassungsfähigkeit des Projekts unnötig einzuschränken @Heikkilä7302452, @INAYAT2015915.

Organisatorisch sollte die Dokumentationspflege Bestandteil der jeweiligen Entwicklungsaufgabe sein @articleStettina. Da sie trotz ihres wahrgenommenen Nutzens im Projektalltag häufig vernachlässigt wird, sind klare Zuständigkeiten und regelmäßige Überprüfungen erforderlich @articleStettina. Dies kann beispielsweise durch Dokumentationsanforderungen in der Definition of Done, Seitenverantwortliche sowie feste Review- und Archivierungsintervalle erfolgen @articleStettina.

Ein allgemeingültiger fester Zeitanteil ist nicht zweckmäßig. Der erforderliche Aufwand hängt von Komplexität, Kritikalität, Lebensdauer und Veränderungshäufigkeit ab @Boehm1504661, @Islam10197828. Er sollte daher bedarfs- und risikoorientiert festgelegt werden, sodass ausreichende Nachvollziehbarkeit entsteht, ohne den Entwicklungsfortschritt unverhältnismäßig zu beeinträchtigen @Boehm1504661, @Islam10197828.