= Praxisbezug
== Projektbeschreibung von Finrep
IDL Finrep ist eine Windows-Desktop-Anwendung zur Erstellung und Validierung regulatorischer Finanzmeldungen. Sie unterstützt Banken bei der Erfüllung ihrer Meldepflichten gegenüber europäischen Zentralbanken und verarbeitet hierfür verschiedene Berichtsstandards, insbesondere FINREP. Neben dem Import und der Zuordnung von Finanzdaten umfasst die Anwendung Validierungs-, Auswertungs- und Exportfunktionen. Aufgrund der langen Projektlaufzeit, der regulatorischen Anforderungen und der regelmäßigen Anpassung an neue Taxonomien handelt es sich um ein fachlich komplexes und kontinuierlich weiterentwickeltes Softwaresystem.
== Bewertung bestehender Dokumentation und #linebreak() Dokumentationspraktiken
Die Dokumentationslandschaft von Finrep ist insgesamt umfangreich und setzt sich aus unterschiedlichen Artefakten zusammen. Im Repository befindet sich eine ausführliche README-Datei. Zusätzlich stehen in Confluence unter anderem eine Architekturübersicht, ein Benutzerhandbuch, ein Installationsleitfaden, eine FAQ-Sammlung, ein Glossar, Berechtigungsmatrizen sowie Dokumentationen zu Taxonomien und DPM 2.0 zur Verfügung. Ergänzt werden diese Inhalte durch Sprint-Reviews und strukturierte Jira-Vorgänge, in denen Fehler, Anforderungen, Tests und technische Aufgaben dokumentiert werden.

Hinsichtlich der Zweckmäßigkeit ist die Dokumentation überwiegend positiv zu bewerten. Die meisten Artefakte besitzen einen erkennbaren Verwendungszweck und richten sich an konkrete Zielgruppen. Benutzer- und Installationsleitfäden unterstützen Anwender und Betrieb, während Architektur- und Entwicklungsdokumentationen insbesondere für die Einarbeitung und Wartung relevant sind. Jira-Vorgänge halten Anforderungen, Fehlerbilder und Umsetzungsschritte fest und unterstützen dadurch die Abstimmung innerhalb des Entwicklungsteams. Einschränkend bestehen einzelne inhaltliche Überschneidungen, beispielsweise durch mehrfach vorhandene Feature-Matrizen. Daneben sind weiterhin veraltete oder nicht mehr verwendete Seiten vorhanden, auch wenn diese teilweise entsprechend gekennzeichnet wurden.

Die Relevanz der dokumentierten Inhalte ist ebenfalls grundsätzlich hoch. Insbesondere die Architekturübersicht und zahlreiche Jira-Vorgänge halten Informationen fest, die nicht unmittelbar aus dem Quellcode hervorgehen. Hierzu gehören fachliche Hintergründe, kundenspezifische Anforderungen, technische Einschränkungen und Begründungen für bestimmte Entscheidungen. Damit wird ein Teil des für die Weiterentwicklung wichtigen Kontextwissens dauerhaft verfügbar gemacht.

Defizite zeigen sich vor allem bei der Dokumentation innerhalb des Quellcodes. Zentrale Geschäftsobjekte enthalten teilweise keine erläuternden Kommentare. Auch Datenzugriffsmethoden mit eingebetteten SQL-Anweisungen dokumentieren nicht immer ausreichend, welchem Zweck eine Abfrage dient und welche Tabellen oder fachlichen Prozesse davon betroffen sind. Bei komplexen Berechnungs- und Validierungsabläufen besteht dadurch eine starke Abhängigkeit vom Erfahrungswissen einzelner Teammitglieder. Der zeitweise Verlust von Detailwissen zur Einbindung einer Berechnungsengine während der Taxonomieumstellung verdeutlicht dieses Risiko.

Die Aktualisierbarkeit der Dokumentation ist differenziert zu bewerten. Positiv ist die hohe Pflegeaktivität. Zahlreiche Seiten wurden im Jahr 2026 überarbeitet, und durch Sprint-Reviews entstehen fortlaufend neue Informationen. Die im Projekt eingesetzte Concurrent Documentation verfolgt außerdem den Ansatz, Dokumentation parallel zur Entwicklung zu erstellen. Dies reduziert das Risiko, dass Dokumentationsaufgaben dauerhaft aufgeschoben werden.

Gleichzeitig enthalten einzelne Dokumente konkrete Servernamen, absolute Netzwerkpfade, Versionsnummern oder Taxonomiebezeichnungen. Solche Angaben können sich kurzfristig ändern und erhöhen den Pflegeaufwand. Auch die Architekturübersicht stellt lediglich eine datierte Momentaufnahme dar. Ohne regelmäßige oder automatisierte Aktualisierung besteht die Gefahr, dass sie nicht mehr mit dem tatsächlichen Stand des Systems übereinstimmt. Unvollständige Platzhalter für Abbildungen zeigen zudem, dass parallel erstellte Dokumentation nicht in jedem Fall vollständig abgeschlossen wird.

Bei Auffindbarkeit und Verständlichkeit bestehen sowohl Stärken als auch Schwächen. Ein zentraler Confluence-Bereich, Inhaltsverzeichnisse, ein Glossar, Jira-Komponenten sowie Verknüpfungen zwischen Jira und dem Repository unterstützen die Suche nach Informationen. Die Dokumentation ist jedoch auf mehrere Bereiche und teilweise persönliche Ablageorte verteilt. Zusätzlich wechseln Sprache und Benennung zwischen Deutsch und Englisch. In einzelnen Fällen tritt dieser Wechsel sogar innerhalb desselben Dokuments auf. Dubletten, uneinheitliche Bezeichnungen und technisch schwer darstellbare Diagramme erschweren damit eine schnelle Orientierung.

Unter Berücksichtigung des Projektkontexts ist der vorhandene Dokumentationsumfang insgesamt angemessen. Finrep ist ein langlebiges, fachlich komplexes und regulatorisch relevantes System mit mehreren Schnittstellen und produktivem Kundeneinsatz. Eine minimale Dokumentation wäre für dieses Projekt daher nicht ausreichend. Die bestehenden Defizite betreffen weniger die Menge als vielmehr die Konsistenz, Aktualität und gezielte Dokumentation besonders komplexer Bereiche.
== Handlungsempfehlung
Aus der Bewertung ergibt sich nicht die Notwendigkeit, den Dokumentationsumfang pauschal zu erhöhen. Stattdessen sollte der vorhandene Aufwand gezielter auf Inhalte konzentriert werden, bei denen fehlende oder veraltete Informationen ein hohes Risiko für Entwicklung, Wartung oder Betrieb darstellen.

Zunächst sollte die Dokumentation im Quellcode an fachlich und technisch komplexen Stellen ergänzt werden. Hierzu gehören insbesondere die Berechnungs- und Validierungslogik, zentrale Geschäftsobjekte sowie Datenzugriffsmethoden mit umfangreichen SQL-Abfragen. Kommentare sollten nicht lediglich die sichtbare Implementierung wiederholen, sondern den Zweck, fachliche Besonderheiten, relevante Parameter und betroffene Datenstrukturen erläutern. Eine flächendeckende Kommentierung sämtlicher Klassen und Methoden ist dagegen nicht erforderlich.

Dokumente, die aus dem aktuellen Systemzustand abgeleitet werden können, sollten möglichst automatisiert erzeugt werden. Dies betrifft insbesondere die Architekturübersicht. Eine Einbindung der Generierung in die bestehende Continuous-Integration-Pipeline könnte sicherstellen, dass Architekturinformationen regelmäßig aktualisiert und mit einem Erstellungsdatum sowie dem zugehörigen Quellcode-Stand versehen werden. Veränderliche Angaben wie Servernamen, Netzwerkpfade oder Versionsbezeichnungen sollten außerdem nicht mehrfach in Fließtexten gepflegt, sondern über zentrale Konfigurationen oder Verweise eingebunden werden.

Zur Verbesserung der Auffindbarkeit sollte eine zentrale Einstiegsseite geschaffen werden, von der aus die wesentlichen Dokumentationsbereiche erreichbar sind. Inhaltlich ähnliche Seiten sollten zusammengeführt und nicht mehr verwendete Dokumente archiviert werden. Zusätzlich sollte für unterschiedliche Dokumenttypen eine einheitliche Sprache festgelegt werden. Beispielsweise könnten technische Dokumentationen überwiegend auf Englisch und kunden- oder supportbezogene Inhalte auf Deutsch geführt werden. Entscheidend ist dabei weniger die gewählte Sprache als deren konsequente Verwendung.

Die Dokumentationspflege sollte stärker organisatorisch in den Entwicklungsprozess eingebunden werden. Bei Änderungen an dokumentierten Funktionen sollte bereits innerhalb der jeweiligen Story oder Fehlerbehebung geprüft werden, ob auch README-Dateien, Confluence-Seiten oder Betriebsanleitungen angepasst werden müssen. Eine entsprechende Prüfung kann als Bestandteil der Definition of Done festgelegt werden. Für zentrale Dokumente sollten außerdem verantwortliche Personen sowie regelmäßige Überprüfungs- und Archivierungsintervalle bestimmt werden.

Technische Entscheidungen mit langfristigen Auswirkungen sollten durch kurze Architecture Decision Records festgehalten werden. Dadurch können nicht nur die getroffenen Entscheidungen, sondern auch ihre Ausgangssituation, Begründung und mögliche Alternativen nachvollzogen werden. Dies ist insbesondere bei Taxonomieumstellungen, der Auswahl von Berechnungsmechanismen oder Änderungen an externen Schnittstellen sinnvoll.

Bei begrenzten zeitlichen Ressourcen sollte die Dokumentation risikobasiert priorisiert werden. Vorrangig zu behandeln sind die Zentralbank-Schnittstellen, die Taxonomie- und Importprozesse sowie die Berechnungs- und Validierungslogik. Diese Bereiche sind für den Betrieb besonders kritisch und zugleich nur mit hohem Aufwand aus dem Quellcode rekonstruierbar.

Insgesamt benötigt Finrep daher nicht grundsätzlich mehr Dokumentation, sondern eine konsistentere, leichter auffindbare und dauerhaft aktualisierbare Dokumentationsbasis. Durch gezielte In-Code-Dokumentation, automatisierte Aktualisierung, klare Verantwortlichkeiten und eine risikobasierte Priorisierung kann das vorhandene Projektwissen besser gesichert werden, ohne den agilen Entwicklungsprozess durch unverhältnismäßigen Dokumentationsaufwand zu belasten.