= Praxisbezug
== Projektbeschreibung von Finrep
IDL Finrep ist eine Windows-Desktop-Anwendung zur Erstellung und Validierung regulatorischer Finanzmeldungen. Sie unterstützt Banken bei ihren Meldepflichten gegenüber europäischen Zentralbanken und verarbeitet insbesondere den Berichtsstandard FINREP. Neben Import und Zuordnung von Finanzdaten umfasst die Anwendung Validierungs-, Auswertungs- und Exportfunktionen. Die lange Projektlaufzeit, regelmäßige Taxonomieänderungen und regulatorische Anforderungen machen Finrep zu einem fachlich komplexen und kontinuierlich weiterentwickelten System.
== Bewertung bestehender Dokumentation und #linebreak() Dokumentationspraktiken
Die Dokumentationslandschaft von Finrep ist umfangreich und besteht aus unterschiedlichen Artefakten. Im Repository befindet sich eine ausführliche README-Datei. In Confluence stehen unter anderem eine Architekturübersicht, Benutzer- und Installationsanleitungen, FAQ, Glossar, Berechtigungsmatrizen sowie Dokumentationen zu Taxonomien und DPM 2.0 zur Verfügung. Sprint-Reviews und strukturierte Jira-Vorgänge ergänzen diese Inhalte durch Informationen zu Fehlern, Anforderungen, Tests und technischen Aufgaben.

Hinsichtlich der Zweckmäßigkeit ist die Dokumentation überwiegend positiv zu bewerten. Die meisten Artefakte besitzen einen erkennbaren Verwendungszweck und richten sich an konkrete Zielgruppen. Benutzer- und Installationsleitfäden unterstützen Anwender und Betrieb, während Architektur- und Entwicklungsdokumentationen der Einarbeitung und Wartung dienen. Jira-Vorgänge sichern Anforderungen, Fehlerbilder und Umsetzungsschritte. Einschränkend bestehen einzelne Überschneidungen, etwa mehrfach vorhandene Feature-Matrizen, sowie weiterhin auffindbare Altseiten, die teilweise lediglich als nicht mehr verwendet gekennzeichnet sind.

Auch die Relevanz der Inhalte ist grundsätzlich hoch. Architekturübersicht und Jira-Vorgänge halten fachliche Hintergründe, kundenspezifische Anforderungen, technische Einschränkungen und Begründungen fest, die nicht unmittelbar aus dem Quellcode hervorgehen. Dadurch bleibt ein wesentlicher Teil des Kontextwissens für die Weiterentwicklung verfügbar.

Defizite zeigen sich vor allem innerhalb des Quellcodes. Zentrale Geschäftsobjekte enthalten teilweise keine erläuternden Kommentare. Bei Datenzugriffsmethoden mit eingebetteten SQL-Anweisungen fehlen mitunter Hinweise zu Zweck, betroffenen Tabellen und fachlichen Prozessen. Auch komplexe Berechnungs- und Validierungsabläufe sind teilweise stark vom Erfahrungswissen einzelner Teammitglieder abhängig. Der zeitweise Verlust von Detailwissen zur Einbindung einer Berechnungsengine während einer Taxonomieumstellung verdeutlicht das daraus entstehende Risiko.

Die Aktualisierbarkeit ist differenziert zu bewerten. Positiv sind die hohe Pflegeaktivität, zahlreiche Überarbeitungen im Jahr 2026 und die fortlaufenden Sprint-Reviews. Der Ansatz der Concurrent Documentation unterstützt zudem die parallele Erstellung von Software und Dokumentation. Gleichzeitig enthalten einzelne Dokumente volatile Angaben wie Servernamen, absolute Netzwerkpfade, Versionsnummern oder Taxonomiebezeichnungen. Solche Inhalte erhöhen den Pflegeaufwand und können schnell veralten. Die Architekturübersicht ist lediglich eine datierte Momentaufnahme; ohne regelmäßige oder automatisierte Erzeugung besteht ein Drift-Risiko. Offene Platzhalter für Abbildungen zeigen außerdem, dass parallel begonnene Dokumentation nicht immer vollständig abgeschlossen wird.

Bei Auffindbarkeit und Verständlichkeit bestehen ebenfalls Stärken und Schwächen. Ein zentraler Confluence-Bereich, Inhaltsverzeichnisse, Glossar, Jira-Komponenten und Verknüpfungen zum Repository unterstützen die Orientierung. Zugleich sind Inhalte auf mehrere Bereiche und teilweise persönliche Ablageorte verteilt. Sprache und Benennung wechseln zwischen Deutsch und Englisch, teilweise innerhalb desselben Dokuments. Dubletten, uneinheitliche Begriffe und schwer darstellbare Diagramme erschweren dadurch die Suche und das Verständnis.

Unter Berücksichtigung des Projektkontexts ist der vorhandene Umfang insgesamt angemessen. Finrep ist langlebig, fachlich komplex, regulatorisch relevant und mit mehreren externen Systemen verbunden. Ein lediglich minimaler Dokumentationsumfang würde diesen Bedingungen nicht gerecht. Der Verbesserungsbedarf ist daher weniger quantitativ als qualitativ: Wissen muss an kritischen Stellen besser im Code gesichert, technische Übersichten gegen Veraltung geschützt und die Dokumentationslandschaft konsistenter strukturiert werden.
== Handlungsempfehlung
Aus der Bewertung ergeben sich mehrere bedarfsorientierte Maßnahmen. Der Aufwand sollte nicht pauschal erhöht, sondern auf kritische, langlebige und schwer rekonstruierbare Bereiche konzentriert werden.

Zunächst sollte die In-Code-Dokumentation gezielt ergänzt werden. Besonders relevant sind zentrale Geschäftsobjekte, die Berechnungs- und Validierungslogik sowie Datenzugriffsmethoden mit eingebettetem SQL. Kurze Kommentare sollten Zweck, Parameter, fachliche Besonderheiten und betroffene Tabellen erläutern. Eine flächendeckende Kommentierung ist nicht erforderlich; entscheidend sind komplexe Stellen, deren Bedeutung nicht direkt aus dem Code hervorgeht.

Technische Momentaufnahmen sollten besser gegen Veraltung abgesichert werden. Die Architekturübersicht kann automatisiert in der Continuous-Integration-Pipeline erzeugt und mit Generierungsdatum sowie Quellstand versehen werden. Veränderliche Servernamen, Pfade, Versions- oder Taxonomiesuffixe sollten möglichst in zentralen Konfigurationen gepflegt oder verlinkt werden, statt mehrfach in Fließtext aufzutreten.

Darüber hinaus sollten Sprache und Struktur vereinheitlicht werden. Für technische Dokumentation bietet sich eine einheitliche Leitsprache an, während kunden- oder supportorientierte Inhalte bei Bedarf weiterhin deutschsprachig bleiben können. Dubletten wie mehrfach vorhandene Feature-Matrizen sollten zusammengeführt werden. Eine zentrale Einstiegsseite sollte die wichtigsten Dokumente, Zielgruppen und Ablageorte übersichtlich verknüpfen.

Die Dokumentationspflege sollte organisatorisch verankert werden. Relevante Aktualisierungen können als Bestandteil der Definition of Done behandelt werden. Klare Seitenverantwortliche und regelmäßige Review- und Archivierungsintervalle verhindern, dass unvollständige oder veraltete Inhalte dauerhaft in der aktiven Struktur verbleiben. Concurrent Documentation sollte konsequent abgeschlossen werden; offene Platzhalter sind entweder zu ergänzen oder sichtbar als Entwurf zu kennzeichnen.

Für wichtige technische Entscheidungen bieten sich leichtgewichtige Architecture Decision Records an. Dadurch können nicht nur Ergebnisse, sondern auch Ausgangslage, Begründung und verworfene Alternativen nachvollzogen werden. Dies ist insbesondere bei Taxonomieumstellungen, Berechnungsmechanismen und externen Schnittstellen sinnvoll.

Bei begrenzten Ressourcen sollte die Dokumentation risikobasiert priorisiert werden. Vorrang besitzen Zentralbank-Schnittstellen, Taxonomie- und Importprozesse sowie Berechnungs- und Validierungslogik, da diese Bereiche betriebs- und fachkritisch sind und sich nur mit hohem Aufwand aus dem Code rekonstruieren lassen. Finrep benötigt somit nicht grundsätzlich mehr Dokumentation, sondern eine konsistentere, leichter auffindbare und dauerhaft aktualisierbare Dokumentationsbasis.